# Generated by Django 4.2.16 on 2024-09-29 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=11)),
                ('tanda_labor', models.CharField(max_length=50)),
                ('fecha_ingreso', models.DateField()),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('numero_serial', models.CharField(max_length=50)),
                ('service_tag', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TecnologiaConexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=11)),
                ('numero_carnet', models.CharField(max_length=20)),
                ('tipo_usuario', models.CharField(choices=[('Profesor', 'Profesor'), ('Estudiante', 'Estudiante'), ('Empleado', 'Empleado')], max_length=50)),
                ('tipo_persona', models.CharField(choices=[('Física', 'Física'), ('Jurídica', 'Jurídica')], max_length=20)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField(auto_now_add=True)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAudiovisualApp.empleado')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAudiovisualApp.equipo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAudiovisualApp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAudiovisualApp.marca')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAudiovisualApp.marca'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAudiovisualApp.modelo'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='tecnologia_conexion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAudiovisualApp.tecnologiaconexion'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='tipo_equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAudiovisualApp.tipoequipo'),
        ),
    ]
